### ISSUE TITLE
example of pseudocolor filter usage which use jet color map

### ISSUE THREAD

**Issue by richardpl** [amiaopensource/ffmpeg-artschool#14]
Here is example one for yuv input: change last argument, i to 0/1/2 if you want to color luma/chroma plane.

`pseudocolor='if(between(val,0,85),lerp(45,159,(val-0)/(85-0)),if(between(val,85,170),lerp(159,177,(val-85)/(170-85)),if(between(val,170,255),lerp(177,70,(val-170)/(255-170))))):if(between(val,0,85),lerp(205,132,(val-0)/(85-0
)),if(between(val,85,170),lerp(132,59,(val-85)/(170-85)),if(between(val,170,255),lerp(59,100,(val-170)/(255-170))))):if(between(val,0,85),lerp(110,59,(val-0)/(85-0)),if(between(val,85,170),lerp(59,127,(val-85)/(170-85)),if(b
etween(val,170,255),lerp(127,202,(val-170)/(255-170))))):i=0'`

**Comment by iamdamosuzuki** [comment]
We added a new script for this called jetcolor.sh
