### ISSUE TITLE
ps1 issue 2: resulting file location

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmpeg-artschool#23]
noticing a diff bet bash and powershell: in bash, all newly created files are located alongside original files; in the powershell everything is going to powershell_scripts folder

**Comment by retokromer** [comment]
(If you use `diff -s` in Bash and `fc` in PowerShell, you get the same result. BTW: if you use Terminal in Windows, you can use the same commands as in Linux/macOS.)

**Comment by nkrabben** [comment]
Oh I think I misinterpreted what Morgan was doing with relpaths. I'll change this.

To confirm `script.ps1 ~/Downloads/video.mp4` should output to `~/Downloads/video_script.mp4`?

**Comment by nkrabben** [comment]
made the change 1377eb5
