### ISSUE TITLE
Sample output to be sure scripts are crossplatform

### ISSUE THREAD

**Issue by nkrabben** [amiaopensource/ffmpeg-artschool#5]
Can someone run off a folder of sample files from the bash scripts so I can be sure that my powershell versions are still doing the same actions?

**Comment by bturkus** [comment]
Sorry, not sure what you mean here. Are the cat and skull videos not right for testing? Or are you talking about running individual scripts on a folder full of files?

**Comment by nkrabben** [comment]
I'm definitely making files, but I'm not sure if the adjustments I have to make are messing up the results in some way. For example, I'm getting a lot of very pink videos. I think that's okay but maybe not???

What I would like is a folder full of default runs of each script with cat and/or skull so I can compare my windows version to it.

Sample videos can go in our google drive folder, not in this repo.

**Comment by bturkus** [comment]
Got it got it. I can work on that tomorrow if no one jumps on it sooner. Good call. The only i was getting in testing most everything yesterday was convolve, which I will send an issue about in now. 

Are you having to mess with the actual filter complex chains to get the scripts to work?

**Comment by nkrabben** [comment]
I have to mess with the quoting and inserting variable values. I don't think I've messed up any filter chains, but I'm not sure  with all the nested brackets, quotes, and colons. Plus I know at least two of the scripts I've converted fail to work as of right now.

**Comment by bturkus** [comment]
Well thanks for putting in this effort! It’ll make the whole thing that much more useful as a longer term reference for folks.

**Comment by bturkus** [comment]
think the scripts page resolves this, closing
